#set(${VIEWMODEL}="${NAME}ViewModel")
#set(${OVERVIEWSTATE}="${NAME}OverviewState")
#set(${DETAILSTATE}="${NAME}DetailState")
#set(${LISTDETAILVIEW}="${NAME}ListDetailView")
#set(${LISTVIEW}="${NAME}ListView")
#parse("List-Detail Screen.kt")